title:     Idle Words
tagline:   'Thoughts on research, life, etc'
url:       https://nightingal3.github.io
baseurl:   '/blog'

author:
  name:  Emmy Liu
  url:   https://twitter.com/_emliu
  email: emmy.liu.1998@gmail.com

plugins:
  - jekyll-paginate

markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true